Loaderarm
gwsystems/composite pull request #423
Opened 2021-06-30 13:40 UTC by betahxy

### Summary of this Pull Request (PR)

**Add description here.**

### Intent for your PR

Choose one (Mandatory):

- [x] This PR is for a code-review and is intended to get feedback, but not to be pulled yet.
- [ ] This PR is mature, and ready to be integrated into the repo.

### Reviewers (Mandatory):
(Specify @<github.com username(s)> of the reviewers. Ex: @user1, @user2)

### Code Quality

As part of this pull request, I've considered the following:

[Style](https://github.com/gparmer/composite/raw/ppos/doc/style_guide/composite_coding_style.pdf):

- [x] Comments adhere to the Style Guide (SG)
- [x] Spacing adhere's to the SG
- [x] Naming adhere's to the SG
- [x] All other aspects of the SG are adhered to, or exceptions are justified in this pull request
- [ ] I have run the auto formatter on my code before submitting this PR (see doc/auto_formatter.md for instructions)

[Code Craftsmanship](http://www2.seas.gwu.edu/~gparmer/posts/2016-03-07-code-craftsmanship.html):

- [x] I've made an attempt to remove all redundant code
- [x] I've considered ways in which my changes might impact existing code, and cleaned it up
- [x] I've formatted the code in an effort to make it easier to read (proper error handling, function use, etc...)
- [x] I've commented appropriately where code is tricky
- [x] I agree that there is no "throw-away" code, and that code in this PR is of high quality

### Testing

I've tested the code using the following test programs (provide list here):

- [ ] micro_booter
- [ ] unit_pingpong
- [ ] unit_schedtests
- [ ] ...(add others here)

2021-06-30 18:04 UTC, gparmer commented
Please add Wenyuan, me and Bite to the listed reviewers.

2021-06-30 18:05 UTC, gparmer commented
Rename this PR as something appropriate: "Add x86-64 into the loaderarm branch". There is no mention of the main core of the PR: x86-64!!!

2021-06-30 18:06 UTC, gparmer commented
Have you tested that the 32 it x86 still works on this?

2021-07-02 12:23 UTC, betahxy commented
> Have you tested that the 32 it x86 still works on this?

Not yet. You're right, I need to test it.

2021-07-03 15:24 UTC, gparmer requested changes
Most of the feedback is very small things. You did a really great job on this!

We do want to strongly consider sharing implementations with 32 bit x86 for a lot of this. Many files seem like they are identical, or lightly changed.

I've posted questions throughout the code review. You should consider the questions, but you should NOT answer them here. I won't be able to keep up with the conversation using github interfaces. If you want to discuss anything, we can chat on slack.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/gdt.c
> +flash_selectors(void)
I don't know what this does from the name. The assembly isn't very self-documenting, so a good name, and potentially a comment is pretty necessary. What problem is this solving that isn't necessary on x86-32 (or is this adapted from there?).

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/hpet.c
> +#include <thd.h>
Share this file with x86-32? symblink

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/idt.c
> +#include "kernel.h"
share with x86-32.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/isr.h
> +#ifndef ISR_H
share with x86-32?

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/kernel.c
> +	//glb_memlayout.mod_start = &end + 1024;
remove commented out code.

If this FIXME is relevant, it should likely be fixed, I'd imagine.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/kernel.c
> +	if (mboot_addr & 7)
style (likely fixed with the format script).

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/kernel.c
> +    {
Indentation and style are off.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/kernel.c
> +                                       + ((tag->size + 7) & ~7)))
Consider isolating this stuff in an multiboot file. Is the 7 magic; perhaps a name would be helpful.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/kernel.h
> +#ifndef KERNEL_H
shared with 32?

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/lapic.c
> +#include "kernel.h"
shared

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/loader.S
> +loader:
There are a lot of fixmes here. This seems like it needs to be cleaned up.

I'm a little surprized with the use of movq before switching to 64 bit, but I don't remember any of the details here, so it is likely OK.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/loader.S
> +	movw    %cs, %ax
When you get to fixing this, you have to remember that the APs boot up into 16 bit. So you can't just change instructions to `q` variants, and use 64 bit registers.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/mem_layout.h
> + * |-------|KKKKKKKK|WWWWW|BBBBBBBB|AA|UUUUUUUUUUUUUUUUUUU|
Validate that this image is up-to-date.

Perhaps share this file.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/miniacpi.c
> +#include "kernel.h"
share.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/multiboot.h
> +#ifndef MULTIBOOT_H
share or remove?

Should we be using multiboot2 for x86-32 as well?

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/multiboot2.h
> +#ifndef _MULTIBOOT2_HEADER_H_
remove starting and trailing `_`. We don't do that consistently.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/ppos.sh
> +#!/bin/sh
remove.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/printk.c
> +#include "string.h"
Shared? Can it be?

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/qemu.sh
> +#!/bin/sh
remove, perhaps. I don't know if this is still necessary.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/serial.c
> +#define ENABLE_SERIAL
shared?

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/start.S
> +#include "chal/shared/cos_config.h"
If this replaces loader.S, then remove loader.s. However, there is some code in there that we likely want (smp).

I don't see a reason to not just move this into loader.S and keep the file names consistent with 32 bit.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/string.c
> +#include "string.h"
shared

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/string.h
> +#ifndef STRING_H
shared.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/tss.c
> +#include "kernel.h"
shared

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/tss.h
> +struct tss
style (`{` on the same line)

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/user.c
> +#include "kernel.h"
unnecessar5y file, perhaps.

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/vga.c
> +/*
shared

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/vtxprintf.c
> +/*  vtxprintf.c, from
shared (after updating 32?)

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/vtxprintf.h
> +/*
Update 32 and share?

2021-07-03 15:24 UTC, gparmer commented on src/platform/x86/x86_64/vm.c
> +u8_t *mem_boot_alloc(int npages) /* boot-time, bump-ptr heap */
`u8_t *` on separate line.

2021-07-19 15:31 UTC, closed without merging